import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { FlyingIcon } from '../components/animation/FlyingIcon';
import { AuthCallback } from '../components/auth/AuthCallback';
import { AuthModal } from '../components/auth/AuthModal';
import { CartSidebar } from '../components/cart/CartSidebar';
import { Footer } from '../components/layout/Footer';
import { Header } from '../components/layout/Header';
import { ProductDetailModal } from '../components/review/ProductDetailModal';
import { NotificationSidebar } from '../components/sidebars/NotificationSidebar';
import { PromotionSidebar } from '../components/sidebars/PromotionSidebar';
import { SupportSidebar } from '../components/sidebars/SupportSidebar';
import { StoreRegistrationModal } from '../components/store/StoreRegistrationModal';
export function AppLayout(props) {
    const { children, user, isLoggedIn, onLogin, onRegister, onLogout, onLoginSuccess, onRegisterSuccess, onAuthCallbackSuccess, showAuthCallback, cartItems, cartItemsCount, totalPrice, onUpdateQuantity, onRemoveItem, onToggleSelectItem, onSelectAllItems, onDeselectAllItems, selectedTotalPrice, selectedItems, onCheckout, onAddToCart, notifications, unreadNotifications, onMarkAsRead, onMarkAllAsRead, onDeleteNotification, onFilterClick, promotions, onPromotionClick, onClaimPromotion, onUsePromotion, faqs, supportTickets, onSupportClick, onSubmitTicket, onStoreClick, onLogoClick, searchQuery, onSearchChange, onSearchClick, onProfileClick, onOrdersClick, isCartOpen, onCartClick, onCartClose, onOpenCheckout, isNotificationOpen, onNotificationClick, onNotificationClose, isPromotionOpen, onPromotionClose, isSupportOpen, onSupportClose, isCheckoutOpen, onCheckoutClose, isAuthOpen, onAuthClose, authTab, isProductDetailOpen, onProductDetailClose, selectedProduct, isStoreRegistrationOpen, onStoreRegistrationClose, onStoreRegistration, flyingIcons, onAnimationComplete, onTriggerFlyingIcon, cartIconRef, } = props;
    return (_jsxs("div", { className: "min-h-screen bg-background", children: [_jsx(Header, { cartItemsCount: cartItemsCount, unreadNotifications: unreadNotifications, onCartClick: onCartClick || onCartClose, onNotificationsClick: onNotificationClick || (() => { }), onFilterClick: onFilterClick, onPromotionClick: onPromotionClick || (() => { }), onSupportClick: onSupportClick || (() => { }), onStoreClick: onStoreClick, onLogoClick: onLogoClick, isLoggedIn: isLoggedIn, user: user, onLogin: onLogin, onRegister: onRegister, cartItems: cartItems, totalPrice: totalPrice, onLogout: onLogout, onProfileClick: onProfileClick, onOrdersClick: onOrdersClick, searchQuery: searchQuery, onSearchChange: onSearchChange, onSearchClick: onSearchClick, cartIconRef: cartIconRef }), children, _jsx(Footer, {}), _jsx(CartSidebar, { isOpen: isCartOpen, onClose: onCartClose, items: cartItems, onUpdateQuantity: onUpdateQuantity, onRemoveItem: onRemoveItem, onToggleSelectItem: onToggleSelectItem, onSelectAllItems: onSelectAllItems, onDeselectAllItems: onDeselectAllItems, selectedTotalPrice: selectedTotalPrice, selectedItems: selectedItems, onCheckout: () => {
                    // CartSidebar sẽ tự xử lý navigation
                } }), _jsx(NotificationSidebar, { isOpen: isNotificationOpen, onClose: onNotificationClose, notifications: notifications, onMarkAsRead: onMarkAsRead, onMarkAllAsRead: onMarkAllAsRead, onDeleteNotification: onDeleteNotification }), _jsx(PromotionSidebar, { isOpen: isPromotionOpen, onClose: onPromotionClose, promotions: promotions, onClaimPromotion: onClaimPromotion, onUsePromotion: onUsePromotion }), _jsx(SupportSidebar, { isOpen: isSupportOpen, onClose: onSupportClose, faqs: faqs, tickets: supportTickets, onSubmitTicket: onSubmitTicket }), _jsx(AuthModal, { isOpen: isAuthOpen, onClose: onAuthClose, defaultTab: authTab, onLoginSuccess: onLoginSuccess, onRegisterSuccess: onRegisterSuccess }), showAuthCallback && (_jsx(AuthCallback, { onSuccess: onAuthCallbackSuccess })), _jsx(ProductDetailModal, { isOpen: isProductDetailOpen, onClose: onProductDetailClose, product: selectedProduct, onAddToCart: onAddToCart, onTriggerFlyingIcon: onTriggerFlyingIcon, isLoggedIn: isLoggedIn, onLogin: onLogin }), _jsx(FlyingIcon, { icons: flyingIcons, onComplete: onAnimationComplete }), _jsx(StoreRegistrationModal, { isOpen: isStoreRegistrationOpen, onClose: onStoreRegistrationClose, onRegister: onStoreRegistration })] }));
}
